const toggle=document.querySelector('.nav-toggle'),links=document.querySelector('#navlinks');
if(toggle&&links){toggle.addEventListener('click',()=>{const open=links.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});links.addEventListener('click',()=>{links.classList.remove('open');toggle.setAttribute('aria-expanded','false')})}
document.querySelectorAll('[data-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.product').forEach(card=>card.hidden=f!=='all'&&card.dataset.category!==f)}));
document.querySelectorAll('[data-lead-form]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));data.source=form.dataset.source;data.savedAt=new Date().toISOString();try{localStorage.setItem('ecodesk_demo_lead',JSON.stringify(data))}catch{}const status=form.querySelector('.form-status');if(status)status.textContent='Demo enquiry saved locally. Opening your guide…';setTimeout(()=>location.href='thank-you.html',650)}));
const fab=document.querySelector('#chat-fab'),chat=document.querySelector('#chat'),close=document.querySelector('#chat-close'),body=document.querySelector('#chat-body'),chatForm=document.querySelector('#chat-form'),chatText=document.querySelector('#chat-text');
function setChat(open){if(!chat)return;chat.classList.toggle('open',open);chat.setAttribute('aria-hidden',String(!open));if(open)chatText?.focus()}
fab?.addEventListener('click',()=>setChat(!chat.classList.contains('open')));close?.addEventListener('click',()=>setChat(false));
const answers=[[/20|team|people/i,'For a 20-person hybrid team, start with work patterns—not 20 identical desks. Compare the Flex bundle and Scale 20 plan, then document attendance assumptions before deciding.'],[/guide|checklist|download/i,"The free buyer's guide includes a 12-point checklist, bundle comparison and decision worksheet. Open Free guide in the footer or submit the demo form."],[/consult|plan|work/i,'EcoDesk uses three stages: discover the team and constraints, design options with explicit assumptions, then obtain human approval.'],[/price|cost|budget/i,'All prices on this fictional site are synthetic. Use them only to practise metadata, schema, content and conversion analysis.'],[/seo|search|ai/i,'This one website is progressively improved across all ten course activities—from audit and keywords to content, AI Overviews, analytics and agentic governance.']];
function reply(text){const hit=answers.find(([r])=>r.test(text));return hit?hit[1]:"I can help with team bundles, the free buyer's guide, consultation steps, prices, or how this site is used in the SEO course."}
function send(text){if(!text||!text.trim())return;const user=document.createElement('div');user.className='bubble user';user.textContent=text;body.append(user);setTimeout(()=>{const bot=document.createElement('div');bot.className='bubble bot';bot.textContent=reply(text);body.append(bot);body.scrollTop=body.scrollHeight},220);body.scrollTop=body.scrollHeight}
chatForm?.addEventListener('submit',e=>{e.preventDefault();send(chatText.value);chatText.value=''});document.querySelectorAll('[data-chat]').forEach(b=>b.addEventListener('click',()=>send(b.dataset.chat)));
